import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#bbc6e2",
        "on-tertiary-container": "#818380",
        "surface-container-high": "#1f2a3f",
        "outline-variant": "#44474c",
        "tertiary-fixed-dim": "#c6c7c3",
        background: "#071327",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#afc9ea",
        error: "#ffb4ab",
        "on-secondary": "#17324d",
        outline: "#8e9196",
        "tertiary-container": "#181b19",
        "error-container": "#93000a",
        "on-background": "#d7e2ff",
        "primary-container": "#0f1a2e",
        "on-tertiary": "#2f312e",
        "on-secondary-container": "#9eb7d8",
        "on-tertiary-fixed": "#1a1c1a",
        "on-secondary-fixed-variant": "#2f4865",
        primary: "#bbc6e2",
        "on-secondary-fixed": "#001d36",
        "on-surface-variant": "#c4c6cc",
        "surface-bright": "#2e394f",
        "on-primary-fixed": "#101b30",
        surface: "#071327",
        "secondary-fixed": "#d1e4ff",
        "inverse-on-surface": "#263046",
        "surface-container-highest": "#2a354b",
        "primary-fixed": "#d7e2ff",
        "on-tertiary-fixed-variant": "#454745",
        "on-error": "#690005",
        "surface-container-lowest": "#030e22",
        "on-primary-container": "#78839c",
        "surface-container": "#142034",
        tertiary: "#c6c7c3",
        "secondary-container": "#2f4865",
        "on-surface": "#d7e2ff",
        "surface-variant": "#2a354b",
        "on-primary": "#263046",
        "surface-tint": "#bbc6e2",
        secondary: "#afc9ea",
        "on-primary-fixed-variant": "#3c475d",
        "inverse-primary": "#545e76",
        "inverse-surface": "#d7e2ff",
        "surface-container-low": "#101b30",
        "surface-dim": "#071327",
        "tertiary-fixed": "#e2e3df",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-plus-jakarta-sans)", "sans-serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-space-grotesk)", "sans-serif"],
        sans: ["var(--font-manrope)", "sans-serif"],
      },
      keyframes: {
        scan: {
          "0%": { top: "0", opacity: "0" },
          "50%": { opacity: "1" },
          "100%": { top: "100%", opacity: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        scan: "scan 3s linear infinite",
        "fade-in": "fade-in 0.4s ease-out",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
